module.exports = {
  "id": "scope-sizing",
  "name": "Scope sizing",
  "description": "Estimate checklist size, CML count, and evidence photo targets from asset context",
  "category": "Planning",
  "module": "inspect",
  "icon": "CalculatorOutlined",
  "tags": [
    "scope",
    "planning",
    "cml",
    "evidence"
  ],
  "uiDefinition": [
    {
      "id": "input-card",
      "type": "section",
      "title": "Input Parameters",
      "description": "Enter project, site, and asset context",
      "icon": "FormOutlined",
      "order": 1,
      "size": 24
    },
    {
      "id": "general-inputs",
      "type": "group",
      "title": "General Inputs",
      "description": "Asset and scope size",
      "sectionId": "input-card",
      "order": 1,
      "size": 24,
      "collapsible": false
    },
    {
      "id": "asset_type",
      "type": "select",
      "title": "Asset Type",
      "label": "Asset Type",
      "placeholder": "Select asset type",
      "required": true,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": "",
      "options": [
        { "label": "Piping", "value": "piping" },
        { "label": "Pipeline", "value": "pipeline" },
        { "label": "Pressure Vessel", "value": "vessel" },
        { "label": "Column / Tower", "value": "column_tower" },
        { "label": "Reactor", "value": "reactor" },
        { "label": "Heat Exchanger", "value": "heat_exchanger" },
        { "label": "Air Cooler / Fin Fan", "value": "air_cooler" },
        { "label": "Condenser", "value": "condenser" },
        { "label": "Boiler", "value": "boiler" },
        { "label": "Fired Heater / Furnace", "value": "fired_heater" },
        { "label": "Storage Tank", "value": "storage_tank" },
        { "label": "Spherical Tank (Sphere)", "value": "sphere" },
        { "label": "Bullet Tank", "value": "bullet" },
        { "label": "Separator / Drum", "value": "separator_drum" },
        { "label": "Knock-out Drum (KOD)", "value": "knockout_drum" },
        { "label": "Scrubber", "value": "scrubber" },
        { "label": "Absorber", "value": "absorber" },
        { "label": "Evaporator", "value": "evaporator" },
        { "label": "Filter / Strainer", "value": "filter_strainer" },
        { "label": "Pump", "value": "pump" },
        { "label": "Compressor", "value": "compressor" },
        { "label": "Turbine", "value": "turbine" },
        { "label": "PSV / Relief Device", "value": "psv_relief_device" },
        { "label": "Valve", "value": "valve" },
        { "label": "Flare System", "value": "flare_system" },
        { "label": "Stack / Chimney", "value": "stack_chimney" },
        { "label": "Ducting", "value": "ducting" },
        { "label": "Structural Steel", "value": "structural_steel" },
        { "label": "Pipe Support", "value": "pipe_support" },
        { "label": "Heat Tracing", "value": "heat_tracing" },
        { "label": "Insulation System", "value": "insulation_system" },
        { "label": "Cooling Tower", "value": "cooling_tower" },
        { "label": "Agitator / Mixer", "value": "agitator_mixer" },
        { "label": "Manifold", "value": "manifold" },
        { "label": "Header", "value": "header" }
      ]
    },
    {
      "id": "scope_basis",
      "type": "select",
      "title": "Scope Basis",
      "label": "Scope Basis",
      "placeholder": "Select basis",
      "required": false,
      "size": 8,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": "surface_area",
      "options": [
        { "label": "Surface area", "value": "surface_area" },
        { "label": "Linear length", "value": "linear_length" },
        { "label": "Count (items)", "value": "count" },
        { "label": "Points", "value": "points" },
        { "label": "Photos", "value": "photos" },
        { "label": "CMLs", "value": "cmls" }
      ]
    },
    {
      "id": "scope_unit_area",
      "type": "select",
      "title": "Scope Unit",
      "label": "Scope Unit",
      "placeholder": "Select unit",
      "required": false,
      "size": 4,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": "m2",
      "options": [
        { "label": "m²", "value": "m2" },
        { "label": "ft²", "value": "ft2" }
      ],
      "watchField": "scope_basis",
      "showWhen": "surface_area"
    },
    {
      "id": "scope_unit_linear",
      "type": "select",
      "title": "Scope Unit",
      "label": "Scope Unit",
      "placeholder": "Select unit",
      "required": false,
      "size": 4,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": "m",
      "options": [
        { "label": "m", "value": "m" },
        { "label": "ft", "value": "ft" }
      ],
      "watchField": "scope_basis",
      "showWhen": "linear_length"
    },
    {
      "id": "scope_unit_count",
      "type": "select",
      "title": "Scope Unit",
      "label": "Scope Unit",
      "required": false,
      "size": 4,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": "items",
      "options": [ { "label": "items", "value": "items" } ],
      "watchField": "scope_basis",
      "showWhen": "count"
    },
    {
      "id": "scope_unit_points",
      "type": "select",
      "title": "Scope Unit",
      "label": "Scope Unit",
      "required": false,
      "size": 4,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": "points",
      "options": [ { "label": "points", "value": "points" } ],
      "watchField": "scope_basis",
      "showWhen": "points"
    },
    {
      "id": "scope_unit_photos",
      "type": "select",
      "title": "Scope Unit",
      "label": "Scope Unit",
      "required": false,
      "size": 4,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": "photos",
      "options": [ { "label": "photos", "value": "photos" } ],
      "watchField": "scope_basis",
      "showWhen": "photos"
    },
    {
      "id": "scope_unit_cmls",
      "type": "select",
      "title": "Scope Unit",
      "label": "Scope Unit",
      "required": false,
      "size": 4,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": "cmls",
      "options": [ { "label": "cmls", "value": "cmls" } ],
      "watchField": "scope_basis",
      "showWhen": "cmls"
    },
    {
      "id": "scope_meaning",
      "type": "text",
      "title": "Scope Meaning",
      "label": "Scope Meaning (hint)",
      "placeholder": "e.g., exterior surface area",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": ""
    },
    {
      "id": "scope_size",
      "type": "number",
      "title": "Scope Size",
      "label": "Scope Size (units)",
      "placeholder": "Enter scope size",
      "required": true,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "general-inputs",
      "defaultValue": null
    },
    {
      "id": "coverage-settings",
      "type": "group",
      "title": "Coverage & Accessibility",
      "description": "Target coverage and access complexity",
      "sectionId": "input-card",
      "order": 5,
      "size": 24,
      "collapsible": true
    },
    {
      "id": "coverage_percent",
      "type": "number",
      "title": "Coverage %",
      "label": "Coverage (%)",
      "placeholder": "Percent of surface to include in scope",
      "required": false,
      "size": 6,
      "sectionId": "input-card",
      "groupId": "coverage-settings",
      "defaultValue": 100
    },
    {
      "id": "accessibility_complexity",
      "type": "select",
      "title": "Accessibility Complexity",
      "label": "Accessibility Complexity",
      "placeholder": "Select complexity",
      "required": false,
      "size": 6,
      "sectionId": "input-card",
      "groupId": "coverage-settings",
      "defaultValue": "medium",
      "options": [
        { "label": "Low", "value": "low" },
        { "label": "Medium", "value": "medium" },
        { "label": "High", "value": "high" }
      ]
    },
    {
      "id": "evidence_granularity",
      "type": "select",
      "title": "Evidence Granularity",
      "label": "Evidence Granularity",
      "placeholder": "Select detail level",
      "required": false,
      "size": 6,
      "sectionId": "input-card",
      "groupId": "coverage-settings",
      "defaultValue": "standard",
      "options": [
        { "label": "Light", "value": "light" },
        { "label": "Standard", "value": "standard" },
        { "label": "Detailed", "value": "detailed" }
      ]
    },
    {
      "id": "risk-settings",
      "type": "group",
      "title": "Risk & Circuit Context",
      "description": "Risk class and corrosion circuit",
      "sectionId": "input-card",
      "order": 6,
      "size": 24,
      "collapsible": true
    },
    {
      "id": "risk_class",
      "type": "select",
      "title": "Risk Class",
      "label": "Risk Class",
      "placeholder": "Select risk class",
      "required": false,
      "size": 8,
      "sectionId": "input-card",
      "groupId": "risk-settings",
      "defaultValue": "medium",
      "options": [
        { "label": "Low", "value": "low" },
        { "label": "Medium", "value": "medium" },
        { "label": "High", "value": "high" }
      ]
    },
    {
      "id": "corrosion_circuit",
      "type": "text",
      "title": "Corrosion Circuit",
      "label": "Corrosion Circuit",
      "placeholder": "e.g., 10T-201-A",
      "required": false,
      "size": 8,
      "sectionId": "input-card",
      "groupId": "risk-settings",
      "defaultValue": ""
    },
    {
      "id": "small_bore_percent",
      "type": "number",
      "title": "Small Bore Percent",
      "label": "% ≤ NPS 2",
      "placeholder": "Percent of small-bore lines",
      "required": false,
      "size": 8,
      "sectionId": "input-card",
      "groupId": "risk-settings",
      "defaultValue": null
    },
    {
      "id": "environment-material",
      "type": "group",
      "title": "Environment & Material",
      "description": "Factors influencing corrosion & CUI",
      "sectionId": "input-card",
      "order": 7,
      "size": 24,
      "collapsible": true
    },
    {
      "id": "temperature_band",
      "type": "select",
      "title": "Temperature Band",
      "label": "Temperature Band",
      "placeholder": "Select band",
      "required": false,
      "size": 6,
      "sectionId": "input-card",
      "groupId": "environment-material",
      "defaultValue": "-20_to_60C",
      "options": [
        { "label": "< -20°C", "value": "lt_-20C" },
        { "label": "-20°C to 60°C", "value": "-20_to_60C" },
        { "label": "60°C to 120°C", "value": "60_to_120C" },
        { "label": "120°C to 200°C", "value": "120_to_200C" },
        { "label": "> 200°C", "value": "gt_200C" }
      ]
    },
    {
      "id": "service_corrosivity",
      "type": "select",
      "title": "Service Corrosivity",
      "label": "Service Corrosivity",
      "placeholder": "Select level",
      "required": false,
      "size": 6,
      "sectionId": "input-card",
      "groupId": "environment-material",
      "defaultValue": "medium",
      "options": [
        { "label": "Low", "value": "low" },
        { "label": "Medium", "value": "medium" },
        { "label": "High", "value": "high" }
      ]
    },
    {
      "id": "phase",
      "type": "select",
      "title": "Phase",
      "label": "Phase",
      "placeholder": "Select phase",
      "required": false,
      "size": 6,
      "sectionId": "input-card",
      "groupId": "environment-material",
      "defaultValue": "wet",
      "options": [
        { "label": "Wet", "value": "wet" },
        { "label": "Dry", "value": "dry" }
      ]
    },
    {
      "id": "coating_condition",
      "type": "select",
      "title": "Coating Condition",
      "label": "Coating Condition",
      "placeholder": "Select condition",
      "required": false,
      "size": 6,
      "sectionId": "input-card",
      "groupId": "environment-material",
      "defaultValue": "fair",
      "options": [
        { "label": "Good", "value": "good" },
        { "label": "Fair", "value": "fair" },
        { "label": "Poor", "value": "poor" }
      ]
    },
    {
      "id": "external_exposure",
      "type": "select",
      "title": "External Exposure",
      "label": "External Exposure",
      "placeholder": "Select exposure",
      "required": false,
      "size": 6,
      "sectionId": "input-card",
      "groupId": "environment-material",
      "defaultValue": "unsheltered",
      "options": [
        { "label": "Sheltered", "value": "sheltered" },
        { "label": "Unsheltered", "value": "unsheltered" },
        { "label": "Coastal", "value": "coastal" }
      ]
    },
    {
      "id": "policy-context",
      "type": "group",
      "title": "Policy & Baseline Context",
      "description": "Code basis and previous plan",
      "sectionId": "input-card",
      "order": 8,
      "size": 24,
      "collapsible": true
    },
    {
      "id": "code_basis",
      "type": "select",
      "title": "Code Basis",
      "label": "Code Basis",
      "placeholder": "Select basis",
      "required": false,
      "size": 8,
      "sectionId": "input-card",
      "groupId": "policy-context",
      "defaultValue": "api570",
      "options": [
        { "label": "API 510", "value": "api510" },
        { "label": "API 570", "value": "api570" },
        { "label": "API 653", "value": "api653" },
        { "label": "Company Policy", "value": "company_policy" }
      ]
    },
    {
      "id": "baseline_checklist",
      "type": "number",
      "title": "Baseline Checklist Size",
      "label": "Baseline Checklist Size",
      "placeholder": "If previous plan exists",
      "required": false,
      "size": 8,
      "sectionId": "input-card",
      "groupId": "policy-context",
      "defaultValue": null
    },
    {
      "id": "baseline_cmls",
      "type": "number",
      "title": "Baseline CMLs",
      "label": "Baseline CMLs",
      "placeholder": "If previous plan exists",
      "required": false,
      "size": 8,
      "sectionId": "input-card",
      "groupId": "policy-context",
      "defaultValue": null
    },
    {
      "id": "tank-scope-details",
      "type": "group",
      "title": "Tank Scope Details",
      "description": "Geometry and features for tanks",
      "sectionId": "input-card",
      "order": 2,
      "size": 12,
      "collapsible": true,
      "watchField": "asset_type",
      "showWhen": "storage_tank,sphere,bullet"
    },
    {
      "id": "tank_diameter_m",
      "type": "number",
      "title": "Tank Diameter (m)",
      "label": "Tank Diameter (m)",
      "placeholder": "Enter tank diameter",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "tank-scope-details",
      "defaultValue": null
    },
    {
      "id": "tank_height_m",
      "type": "number",
      "title": "Tank Height (m)",
      "label": "Tank Height (m)",
      "placeholder": "Enter tank height",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "tank-scope-details",
      "defaultValue": null
    },
    {
      "id": "roof_type",
      "type": "select",
      "title": "Roof Type",
      "label": "Roof Type",
      "placeholder": "Select roof type",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "tank-scope-details",
      "defaultValue": "",
      "options": [
        { "label": "Fixed roof", "value": "fixed" },
        { "label": "Floating roof", "value": "floating" }
      ]
    },
    {
      "id": "tank_insulation_present",
      "type": "switch",
      "title": "Tank Insulation Present",
      "label": "Insulation Present",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "tank-scope-details",
      "defaultValue": false
    },
    {
      "id": "piping-scope-details",
      "type": "group",
      "title": "Piping Scope Details",
      "description": "Piping-specific details",
      "sectionId": "input-card",
      "order": 3,
      "size": 12,
      "collapsible": true,
      "watchField": "asset_type",
      "showWhen": "piping,pipeline"
    },
    {
      "id": "nps",
      "type": "number",
      "title": "Nominal Pipe Size (NPS)",
      "label": "NPS",
      "placeholder": "Enter NPS",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "piping-scope-details",
      "defaultValue": null
    },
    {
      "id": "fittings_density",
      "type": "select",
      "title": "Fittings Density",
      "label": "Fittings Density",
      "placeholder": "Select density",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "piping-scope-details",
      "defaultValue": "medium",
      "options": [
        { "label": "Low", "value": "low" },
        { "label": "Medium", "value": "medium" },
        { "label": "High", "value": "high" }
      ]
    },
    {
      "id": "piping_insulated",
      "type": "switch",
      "title": "Piping Insulated",
      "label": "Insulated",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "piping-scope-details",
      "defaultValue": false
    },
    {
      "id": "vessel-scope-details",
      "type": "group",
      "title": "Vessel Scope Details",
      "description": "Shell geometry for vessels/columns",
      "sectionId": "input-card",
      "order": 4,
      "size": 12,
      "collapsible": true,
      "watchField": "asset_type",
      "showWhen": "vessel,column_tower,reactor,separator_drum,knockout_drum,scrubber,absorber,evaporator,filter_strainer,condenser,boiler,heat_exchanger,air_cooler"
    },
    {
      "id": "vessel_diameter_m",
      "type": "number",
      "title": "Vessel Diameter (m)",
      "label": "Vessel Diameter (m)",
      "placeholder": "Enter vessel diameter",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "vessel-scope-details",
      "defaultValue": null
    },
    {
      "id": "vessel_height_m",
      "type": "number",
      "title": "Vessel Height (m)",
      "label": "Vessel Height (m)",
      "placeholder": "Enter vessel height",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "vessel-scope-details",
      "defaultValue": null
    },
    {
      "id": "nozzle_density",
      "type": "select",
      "title": "Nozzle Density",
      "label": "Nozzle Density",
      "placeholder": "Select density",
      "required": false,
      "size": 12,
      "sectionId": "input-card",
      "groupId": "vessel-scope-details",
      "defaultValue": "medium",
      "options": [
        { "label": "Low", "value": "low" },
        { "label": "Medium", "value": "medium" },
        { "label": "High", "value": "high" }
      ]
    }
  ],
  "aiPrompt": "You are an expert inspection planner.\n\nContext: Scope sizing — estimate checklist size, CML count, and evidence photo targets from the asset context.\nTask: Using only the inputs above, produce a concise scope sizing output limited strictly to:\n1) Checklist size estimate\n2) CML count estimate\n3) Evidence photo targets (list)\n\nOutput a professional Markdown report with ONLY these sections:\n\n# Scope Sizing Plan\n## Inputs##\n Method and Assumptions\n## Calculations\n- Checklist Size Estimate\n- CML Count Estimate\n- Evidence Photo Targets\n## Summary Table\n(Use columns: Metric | Value | Units | Rationale)\n## References and Standards"
};